// REDUCERS TYPE ACTION
export const GET_TASK_LIST_API = "GET_TASK_LIST_API"

export const DISPLAY_LOADING = "DISPLAY_LOADING"

export const HIDE_LOADING = "HIDE_LOADING"

// SAGA TYPE ACTION
export const GET_TASK_LIST_SAGA = "GET_TASK_LIST_SAGA"

export const ADD_TASK_SAGA = "ADD_TASK_SAGA"

export const DELETE_TASK_SAGA = "DELETE_TASK_SAGA"

export const DONE_TASK_SAGA = "DONE_TASK_SAGA"

export const REJECT_TASK_SAGA = "REJECT_TASK_SAGA"
